Repository hmcts/et-message-handler, pull requests merged in 2022-11, with the labels that each got.

#220 R1.1
  build.gradle
Labels: ns:et, prd:et, rel:et-msg-handler-pr-220

#222 Revert "Merge pull request #220 from hmcts/et-common-version-update-br"
  build.gradle
Labels: ns:et, prd:et, rel:et-msg-handler-pr-222

#223 ret-2690 implementation
  build.gradle
  src/main/java/uk/gov/hmcts/reform/ethos/ecm/consumer/config/CcdClientConfiguration.java
  src/main/java/uk/gov/hmcts/reform/ethos/ecm/consumer/helpers/transfertoecm/TransferToEcmCaseDataHelper.java
  src/main/java/uk/gov/hmcts/reform/ethos/ecm/consumer/service/transfertoecm/CreateEcmSingleService.java
  src/test/java/uk/gov/hmcts/reform/ethos/ecm/consumer/service/transfertoecm/CreateEcmSingleServiceTest.java
Labels: ns:et, prd:et, rel:et-msg-handler-pr-223

#224 R1.1
  build.gradle
Labels: ns:et, prd:et, rel:et-msg-handler-pr-224
