Repository hmcts/et-message-handler, pull requests merged in 2022-08, with the labels that each got.

#191 PMD added
  build.gradle
  config/owasp/suppressions.xml
  config/pmd/ruleset.xml
  src/main/java/uk/gov/hmcts/reform/ethos/ecm/consumer/config/ServiceBusCreateUpdatesReceiverConf.java
  src/main/java/uk/gov/hmcts/reform/ethos/ecm/consumer/config/ServiceBusUpdateCaseReceiverConf.java
  src/main/java/uk/gov/hmcts/reform/ethos/ecm/consumer/config/ServiceTokenGeneratorConfiguration.java
  src/main/java/uk/gov/hmcts/reform/ethos/ecm/consumer/domain/MultipleErrors.java
  src/main/java/uk/gov/hmcts/reform/ethos/ecm/consumer/helpers/Constants.java
  src/main/java/uk/gov/hmcts/reform/ethos/ecm/consumer/helpers/transfertoecm/TransferToEcmCaseDataHelper.java
  src/main/java/uk/gov/hmcts/reform/ethos/ecm/consumer/idam/IdamApi.java
  src/main/java/uk/gov/hmcts/reform/ethos/ecm/consumer/service/EmailService.java
  src/main/java/uk/gov/hmcts/reform/ethos/ecm/consumer/service/MultipleUpdateService.java
  src/main/java/uk/gov/hmcts/reform/ethos/ecm/consumer/service/SingleCreationService.java
  src/main/java/uk/gov/hmcts/reform/ethos/ecm/consumer/service/SingleReadingService.java
  src/main/java/uk/gov/hmcts/reform/ethos/ecm/consumer/service/SingleTransferService.java
  src/main/java/uk/gov/hmcts/reform/ethos/ecm/consumer/service/SingleUpdateService.java
  src/main/java/uk/gov/hmcts/reform/ethos/ecm/consumer/service/UserService.java
  src/main/java/uk/gov/hmcts/reform/ethos/ecm/consumer/service/transfertoecm/CreateEcmSingleService.java
  src/main/java/uk/gov/hmcts/reform/ethos/ecm/consumer/service/transfertoecm/TransferToEcmService.java
  src/main/java/uk/gov/hmcts/reform/ethos/ecm/consumer/tasks/CreateUpdatesBusReceiverTask.java
  src/main/java/uk/gov/hmcts/reform/ethos/ecm/consumer/tasks/UpdateCaseBusReceiverTask.java
  src/test/java/uk/gov/hmcts/reform/ethos/ecm/consumer/helpers/Helper.java
  src/test/java/uk/gov/hmcts/reform/ethos/ecm/consumer/helpers/TransferToEcmCaseDataHelperTest.java
  src/test/java/uk/gov/hmcts/reform/ethos/ecm/consumer/service/AccessTokenServiceTest.java
  src/test/java/uk/gov/hmcts/reform/ethos/ecm/consumer/service/EmailServiceTest.java
  src/test/java/uk/gov/hmcts/reform/ethos/ecm/consumer/service/MultipleUpdateServiceTest.java
  src/test/java/uk/gov/hmcts/reform/ethos/ecm/consumer/service/SingleCreationServiceTest.java
  src/test/java/uk/gov/hmcts/reform/ethos/ecm/consumer/service/SingleReadingServiceTest.java
  src/test/java/uk/gov/hmcts/reform/ethos/ecm/consumer/service/SingleTransferServiceTest.java
  src/test/java/uk/gov/hmcts/reform/ethos/ecm/consumer/service/SingleUpdateServiceTest.java
  src/test/java/uk/gov/hmcts/reform/ethos/ecm/consumer/service/UserServiceTest.java
  src/test/java/uk/gov/hmcts/reform/ethos/ecm/consumer/service/transfertoecm/CreateEcmSingleServiceTest.java
  src/test/java/uk/gov/hmcts/reform/ethos/ecm/consumer/service/transfertoecm/TransferToEcmServiceTest.java
Labels: ns:et, prd:et, rel:et-msg-handler-pr-191

#194 Fix postgresql CVE
  build.gradle
Labels: ns:et, prd:et, rel:et-msg-handler-pr-194

#195 Fix branch merge and CVE issues
  build.gradle
  config/owasp/suppressions.xml
Labels: ns:et, prd:et, rel:et-msg-handler-pr-195

#192 Pi26 ip
  build.gradle
  config/owasp/suppressions.xml
  config/pmd/ruleset.xml
  src/main/java/uk/gov/hmcts/reform/ethos/ecm/consumer/config/ServiceBusCreateUpdatesReceiverConf.java
  src/main/java/uk/gov/hmcts/reform/ethos/ecm/consumer/config/ServiceBusUpdateCaseReceiverConf.java
  src/main/java/uk/gov/hmcts/reform/ethos/ecm/consumer/config/ServiceTokenGeneratorConfiguration.java
  src/main/java/uk/gov/hmcts/reform/ethos/ecm/consumer/domain/MultipleErrors.java
  src/main/java/uk/gov/hmcts/reform/ethos/ecm/consumer/helpers/Constants.java
  src/main/java/uk/gov/hmcts/reform/ethos/ecm/consumer/helpers/transfertoecm/TransferToEcmCaseDataHelper.java
  src/main/java/uk/gov/hmcts/reform/ethos/ecm/consumer/idam/IdamApi.java
  src/main/java/uk/gov/hmcts/reform/ethos/ecm/consumer/service/EmailService.java
  src/main/java/uk/gov/hmcts/reform/ethos/ecm/consumer/service/MultipleUpdateService.java
  src/main/java/uk/gov/hmcts/reform/ethos/ecm/consumer/service/SingleCreationService.java
  src/main/java/uk/gov/hmcts/reform/ethos/ecm/consumer/service/SingleReadingService.java
  src/main/java/uk/gov/hmcts/reform/ethos/ecm/consumer/service/SingleTransferService.java
  src/main/java/uk/gov/hmcts/reform/ethos/ecm/consumer/service/SingleUpdateService.java
  src/main/java/uk/gov/hmcts/reform/ethos/ecm/consumer/service/UserService.java
  src/main/java/uk/gov/hmcts/reform/ethos/ecm/consumer/service/transfertoecm/CreateEcmSingleService.java
  src/main/java/uk/gov/hmcts/reform/ethos/ecm/consumer/service/transfertoecm/TransferToEcmService.java
  src/main/java/uk/gov/hmcts/reform/ethos/ecm/consumer/tasks/CreateUpdatesBusReceiverTask.java
  src/main/java/uk/gov/hmcts/reform/ethos/ecm/consumer/tasks/UpdateCaseBusReceiverTask.java
  src/test/java/uk/gov/hmcts/reform/ethos/ecm/consumer/helpers/Helper.java
  src/test/java/uk/gov/hmcts/reform/ethos/ecm/consumer/helpers/TransferToEcmCaseDataHelperTest.java
  src/test/java/uk/gov/hmcts/reform/ethos/ecm/consumer/service/AccessTokenServiceTest.java
  src/test/java/uk/gov/hmcts/reform/ethos/ecm/consumer/service/EmailServiceTest.java
  src/test/java/uk/gov/hmcts/reform/ethos/ecm/consumer/service/MultipleUpdateServiceTest.java
  src/test/java/uk/gov/hmcts/reform/ethos/ecm/consumer/service/SingleCreationServiceTest.java
  src/test/java/uk/gov/hmcts/reform/ethos/ecm/consumer/service/SingleReadingServiceTest.java
  src/test/java/uk/gov/hmcts/reform/ethos/ecm/consumer/service/SingleTransferServiceTest.java
  src/test/java/uk/gov/hmcts/reform/ethos/ecm/consumer/service/SingleUpdateServiceTest.java
  src/test/java/uk/gov/hmcts/reform/ethos/ecm/consumer/service/UserServiceTest.java
  src/test/java/uk/gov/hmcts/reform/ethos/ecm/consumer/service/transfertoecm/CreateEcmSingleServiceTest.java
  src/test/java/uk/gov/hmcts/reform/ethos/ecm/consumer/service/transfertoecm/TransferToEcmServiceTest.java
Labels: ns:et, prd:et, rel:et-msg-handler-pr-192

#197 Add backstage configuration file
  catalog-info.yaml
Labels: ns:et, prd:et, rel:et-msg-handler-pr-197
