Repository hmcts/et-message-handler, pull requests merged in 2022-10, with the labels that each got.

#215 Update dependencies
  build.gradle
  config/owasp/suppressions.xml
Labels: ns:et, prd:et, rel:et-msg-handler-pr-215

#217 Merge master dependency
  build.gradle
  config/owasp/suppressions.xml
Labels: ns:et, prd:et, rel:et-msg-handler-pr-217

#218 RET-2714
  src/main/resources/application-cftlib.properties
Labels: ns:et, prd:et, rel:et-msg-handler-pr-218

#204 DO NOT MERGE Release 1.1
  build.gradle
  config/owasp/suppressions.xml
  config/pmd/ruleset.xml
  gradle/wrapper/gradle-wrapper.properties
  src/main/java/uk/gov/hmcts/reform/ethos/ecm/consumer/config/ServiceBusCreateUpdatesReceiverConf.java
  src/main/java/uk/gov/hmcts/reform/ethos/ecm/consumer/config/ServiceBusUpdateCaseReceiverConf.java
  src/main/java/uk/gov/hmcts/reform/ethos/ecm/consumer/config/ServiceTokenGeneratorConfiguration.java
  src/main/java/uk/gov/hmcts/reform/ethos/ecm/consumer/domain/MultipleErrors.java
  src/main/java/uk/gov/hmcts/reform/ethos/ecm/consumer/helpers/Constants.java
  src/main/java/uk/gov/hmcts/reform/ethos/ecm/consumer/helpers/transfertoecm/TransferToEcmCaseDataHelper.java
  src/main/java/uk/gov/hmcts/reform/ethos/ecm/consumer/idam/IdamApi.java
  src/main/java/uk/gov/hmcts/reform/ethos/ecm/consumer/service/EmailService.java
  src/main/java/uk/gov/hmcts/reform/ethos/ecm/consumer/service/MultipleUpdateService.java
  src/main/java/uk/gov/hmcts/reform/ethos/ecm/consumer/service/SingleCreationService.java
  src/main/java/uk/gov/hmcts/reform/ethos/ecm/consumer/service/SingleReadingService.java
  src/main/java/uk/gov/hmcts/reform/ethos/ecm/consumer/service/SingleTransferService.java
  src/main/java/uk/gov/hmcts/reform/ethos/ecm/consumer/service/SingleUpdateService.java
  src/main/java/uk/gov/hmcts/reform/ethos/ecm/consumer/service/UserService.java
  src/main/java/uk/gov/hmcts/reform/ethos/ecm/consumer/service/transfertoecm/CreateEcmSingleService.java
  src/main/java/uk/gov/hmcts/reform/ethos/ecm/consumer/service/transfertoecm/TransferToEcmService.java
  src/main/java/uk/gov/hmcts/reform/ethos/ecm/consumer/tasks/CreateUpdatesBusReceiverTask.java
  src/main/java/uk/gov/hmcts/reform/ethos/ecm/consumer/tasks/UpdateCaseBusReceiverTask.java
  src/main/resources/application-cftlib.properties
  src/test/java/uk/gov/hmcts/reform/ethos/ecm/consumer/helpers/Helper.java
  src/test/java/uk/gov/hmcts/reform/ethos/ecm/consumer/helpers/TransferToEcmCaseDataHelperTest.java
  src/test/java/uk/gov/hmcts/reform/ethos/ecm/consumer/service/AccessTokenServiceTest.java
  src/test/java/uk/gov/hmcts/reform/ethos/ecm/consumer/service/EmailServiceTest.java
  src/test/java/uk/gov/hmcts/reform/ethos/ecm/consumer/service/MultipleUpdateServiceTest.java
  src/test/java/uk/gov/hmcts/reform/ethos/ecm/consumer/service/SingleCreationServiceTest.java
  src/test/java/uk/gov/hmcts/reform/ethos/ecm/consumer/service/SingleReadingServiceTest.java
  src/test/java/uk/gov/hmcts/reform/ethos/ecm/consumer/service/SingleTransferServiceTest.java
  src/test/java/uk/gov/hmcts/reform/ethos/ecm/consumer/service/SingleUpdateServiceTest.java
  src/test/java/uk/gov/hmcts/reform/ethos/ecm/consumer/service/UserServiceTest.java
  src/test/java/uk/gov/hmcts/reform/ethos/ecm/consumer/service/transfertoecm/CreateEcmSingleServiceTest.java
  src/test/java/uk/gov/hmcts/reform/ethos/ecm/consumer/service/transfertoecm/TransferToEcmServiceTest.java
Labels: ns:et, prd:et, rel:et-msg-handler-pr-204

#221 batik-all dependency
  build.gradle
Labels: ns:et, prd:et, rel:et-msg-handler-pr-221
