Repository hmcts/et-message-handler, pull requests merged in 2022-03, with the labels that each got.

#95 Bump versions
  build.gradle
  charts/et-msg-handler/Chart.yaml
  charts/et-msg-handler/values.preview.template.yaml
  charts/et-msg-handler/values.yaml
  config/owasp/suppressions.xml
  src/main/java/uk/gov/hmcts/reform/ethos/ecm/consumer/config/SwaggerConfiguration.java
  src/main/java/uk/gov/hmcts/reform/ethos/ecm/consumer/service/AccessTokenService.java
  src/main/resources/application.properties
  src/main/resources/bootstrap.yaml
Labels: ns:et, prd:et, rel:et-msg-handler-pr-95

#98 Merge ECM R5.0.25
  build.gradle
Labels: ns:et, prd:et, rel:et-msg-handler-pr-98

#105 Fix servicebus environment variables
  build.gradle
  charts/et-msg-handler/Chart.yaml
  charts/et-msg-handler/values.preview.template.yaml
Labels: ns:et, prd:et, rel:et-msg-handler-pr-105

#103 jenkins nightly build changes
  Jenkinsfile_nightly
Labels: ns:et, prd:et, rel:et-msg-handler-pr-103

#112 Merge ECM R5.0.26
  build.gradle
Labels: ns:et, prd:et, rel:et-msg-handler-pr-112

#116 Add CVE suppressions for POI
  config/owasp/suppressions.xml
Labels: ns:et, prd:et, rel:et-msg-handler-pr-116

#118 Bump jackson-bom
  build.gradle
Labels: ns:et, prd:et, rel:et-msg-handler-pr-118

#125 Merge ECM R5.0.27
  build.gradle
Labels: ns:et, prd:et, rel:et-msg-handler-pr-125
