Repository hmcts/et-message-handler, pull requests merged in 2022-09, with the labels that each got.

#198 Fix snakeyaml CVE
  build.gradle
Labels: ns:et, prd:et, rel:et-msg-handler-pr-198

#199 Merge master
  build.gradle
  catalog-info.yaml
  config/owasp/suppressions.xml
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  gradlew.bat
Labels: ns:et, prd:et, rel:et-msg-handler-pr-199

#200 Update dependencies
  build.gradle
  config/owasp/suppressions.xml
  renovate.json
Labels: ns:et, prd:et, rel:et-msg-handler-pr-200

#202 Enable application to run in cftlib environment
  README.md
  src/main/resources/application-cftlib.properties
Labels: ns:et, prd:et, rel:et-msg-handler-pr-202

#207 Add ITHC
  Jenkinsfile_CNP
Labels: ns:et, prd:et, rel:et-msg-handler-pr-207

#208 Ret 2048 - RET to ECM case transfer bug fix
  build.gradle
  src/main/java/uk/gov/hmcts/reform/ethos/ecm/consumer/helpers/transfertoecm/TransferToEcmCaseDataHelper.java
  src/main/java/uk/gov/hmcts/reform/ethos/ecm/consumer/service/transfertoecm/CreateEcmSingleService.java
  src/main/java/uk/gov/hmcts/reform/ethos/ecm/consumer/service/transfertoecm/TransferToEcmService.java
  src/test/java/uk/gov/hmcts/reform/ethos/ecm/consumer/helpers/Helper.java
  src/test/java/uk/gov/hmcts/reform/ethos/ecm/consumer/service/transfertoecm/CreateEcmSingleServiceTest.java
  src/test/java/uk/gov/hmcts/reform/ethos/ecm/consumer/service/transfertoecm/TransferToEcmServiceTest.java
Labels: ns:et, prd:et, rel:et-msg-handler-pr-208

#211 Master sprint br conflict fix
  Jenkinsfile_CNP
  README.md
  build.gradle
  config/owasp/suppressions.xml
  gradle/wrapper/gradle-wrapper.properties
  renovate.json
  src/main/resources/application-cftlib.properties
Labels: ns:et, prd:et, rel:et-msg-handler-pr-211

#210 Pi27 sprint4
  Jenkinsfile_CNP
  README.md
  build.gradle
  gradle/wrapper/gradle-wrapper.properties
  src/main/java/uk/gov/hmcts/reform/ethos/ecm/consumer/helpers/transfertoecm/TransferToEcmCaseDataHelper.java
  src/main/java/uk/gov/hmcts/reform/ethos/ecm/consumer/service/transfertoecm/CreateEcmSingleService.java
  src/main/java/uk/gov/hmcts/reform/ethos/ecm/consumer/service/transfertoecm/TransferToEcmService.java
  src/main/resources/application-cftlib.properties
  src/test/java/uk/gov/hmcts/reform/ethos/ecm/consumer/helpers/Helper.java
  src/test/java/uk/gov/hmcts/reform/ethos/ecm/consumer/service/transfertoecm/CreateEcmSingleServiceTest.java
  src/test/java/uk/gov/hmcts/reform/ethos/ecm/consumer/service/transfertoecm/TransferToEcmServiceTest.java
Labels: ns:et, prd:et, rel:et-msg-handler-pr-210
