Repository hmcts/et-message-handler, pull requests merged in 2022-02, with the labels that each got.

#57 feat: upgraded packages
  build.gradle
Labels: ns:et, prd:et, rel:et-msg-handler-pr-57

#58 Bump dependency versions
  build.gradle
Labels: ns:et, prd:et, rel:et-msg-handler-pr-58

#62 Bump dependency versions
  build.gradle
Labels: ns:et, prd:et, rel:et-msg-handler-pr-62

#67 Bump dependency versions
  build.gradle
Labels: ns:et, prd:et, rel:et-msg-handler-pr-67

#70 Merge ECM R5.0.23
  build.gradle
  src/main/java/uk/gov/hmcts/reform/ethos/ecm/consumer/config/HttpClientConfiguration.java
  src/main/resources/application.properties
Labels: ns:et, prd:et, rel:et-msg-handler-pr-70

#71 Bump et-common version to 0.0.19
  build.gradle
Labels: ns:et, prd:et, rel:et-msg-handler-pr-71

#75 Fix CVEs
  build.gradle
  config/owasp/suppressions.xml
Labels: ns:et, prd:et, rel:et-msg-handler-pr-75

#76 Bump java helm chart to 3.7.0
  charts/et-msg-handler/Chart.yaml
Labels: ns:et, prd:et, rel:et-msg-handler-pr-76

#77 Bump versions
  build.gradle
Labels: ns:et, prd:et, rel:et-msg-handler-pr-77

#78 feat: upgraded et-common
  build.gradle
Labels: ns:et, prd:et, rel:et-msg-handler-pr-78

#80 Bump java helm chart version to 3.7.1
  charts/et-msg-handler/Chart.yaml
Labels: ns:et, prd:et, rel:et-msg-handler-pr-80

#86 Merge ECM R5.0.24
  build.gradle
Labels: ns:et, prd:et, rel:et-msg-handler-pr-86

#89 Bump versions
  build.gradle
Labels: ns:et, prd:et, rel:et-msg-handler-pr-89
