Repository hmcts/et-message-handler, pull requests merged in 2022-07, with the labels that each got.

#181 Bump chart versions
  charts/et-msg-handler/Chart.yaml
  charts/et-msg-handler/values.preview.template.yaml
  config/owasp/suppressions.xml
Labels: ns:et, prd:et, rel:et-msg-handler-pr-181

#183 Add Fortify scan nightly build pipeline integration
  Jenkinsfile_nightly
  build.gradle
  config/fortify-client.properties
Labels: ns:et, prd:et, rel:et-msg-handler-pr-183

#184 Bump Java helm chart to 4.0.1
  charts/et-msg-handler/Chart.yaml
Labels: ns:et, prd:et, rel:et-msg-handler-pr-184

#185 Bump testng to 7.6.1
  build.gradle
Labels: ns:et, prd:et, rel:et-msg-handler-pr-185

#186 RET-1861
  build.gradle
  src/main/java/uk/gov/hmcts/reform/ethos/ecm/consumer/helpers/transfertoecm/TransferToEcmCaseDataHelper.java
Labels: ns:et, prd:et, rel:et-msg-handler-pr-186

#188 Bump log4j-api to 2.18.0
  build.gradle
  config/owasp/suppressions.xml
Labels: ns:et, prd:et, rel:et-msg-handler-pr-188

#189 Pi26 s6 update
  config/owasp/suppressions.xml
Labels: ns:et, prd:et, rel:et-msg-handler-pr-189

#187 Pi26 s6
  build.gradle
  src/main/java/uk/gov/hmcts/reform/ethos/ecm/consumer/helpers/transfertoecm/TransferToEcmCaseDataHelper.java
Labels: ns:et, prd:et, rel:et-msg-handler-pr-187
