Repository hmcts/et-message-handler, pull requests merged in 2023-11, with the labels that each got.

#283 Fix cve
  build.gradle
Labels: prd:et, ns:et, rel:et-msg-handler-pr-283

#294 Ret 4236 - Case link
  build.gradle
  config/owasp/suppressions.xml
  src/main/java/uk/gov/hmcts/reform/ethos/ecm/consumer/helpers/transfertoecm/SingleCreationServiceHelper.java
  src/main/java/uk/gov/hmcts/reform/ethos/ecm/consumer/helpers/transfertoecm/TransferToEcmCaseDataHelper.java
  src/main/java/uk/gov/hmcts/reform/ethos/ecm/consumer/service/SingleCreationService.java
  src/main/java/uk/gov/hmcts/reform/ethos/ecm/consumer/service/transfertoecm/CreateEcmSingleService.java
  src/test/java/uk/gov/hmcts/reform/ethos/ecm/consumer/service/transfertoecm/CreateEcmSingleServiceTest.java
  src/test/java/uk/gov/hmcts/reform/ethos/ecm/consumer/tasks/CreateUpdatesBusReceiverTaskTest.java
  src/test/java/uk/gov/hmcts/reform/ethos/ecm/consumer/tasks/UpdateCaseBusReceiverTaskTest.java
Labels: prd:et, ns:et, rel:et-msg-handler-pr-294, enable_keep_helm

#326 CVE and CFTlib changes
  config/owasp/suppressions.xml
  src/main/resources/application-cftlib.properties
Labels: prd:et, ns:et, rel:et-msg-handler-pr-326

#331 Adding chart variable
  charts/et-msg-handler/Chart.yaml
  charts/et-msg-handler/values.yaml
Labels: prd:et, ns:et, rel:et-msg-handler-pr-331
