Repository hmcts/et-message-handler, pull requests merged in 2024-06, with the labels that each got.

#499 RET-5201: Applying Legalrep access to newly created multiple
  build.gradle
  src/main/java/uk/gov/hmcts/reform/ethos/ecm/consumer/service/LegalRepAccessService.java
  src/main/java/uk/gov/hmcts/reform/ethos/ecm/consumer/service/UpdateManagementService.java
  src/test/java/uk/gov/hmcts/reform/ethos/ecm/consumer/service/LegalRepAccessServiceTest.java
  src/test/java/uk/gov/hmcts/reform/ethos/ecm/consumer/service/UpdateManagementServiceTest.java
  src/test/java/uk/gov/hmcts/reform/ethos/ecm/consumer/tasks/UpdateCaseBusReceiverTaskTest.java
Labels: prd:et, ns:et, rel:et-msg-handler-pr-499

#511 Update renovate.json
  renovate.json
Labels: prd:et, ns:et, rel:et-msg-handler-pr-511

#518 RET-5255: Use latest Release of ET-Common
  build.gradle
Labels: prd:et, ns:et, rel:et-msg-handler-pr-518
