Repository hmcts/et-message-handler, pull requests merged in 2024-04, with the labels that each got.

#411 RET-4743 - Bump packages
  build.gradle
  src/test/java/uk/gov/hmcts/reform/ethos/ecm/consumer/service/SingleUpdateServiceTest.java
Labels: prd:et, ns:et, rel:et-msg-handler-pr-411

#406 Remove v11 DB
  charts/et-msg-handler/Chart.yaml
  charts/et-msg-handler/values.yaml
  infrastructure/database.tf
  infrastructure/main.tf
Labels: prd:et, ns:et, destroy, rel:et-msg-handler-pr-406, aat/destroy

#355 RET-4846
  src/main/java/uk/gov/hmcts/reform/ethos/ecm/consumer/service/SingleUpdateService.java
  src/test/java/uk/gov/hmcts/reform/ethos/ecm/consumer/service/SingleUpdateServiceTest.java
Labels: prd:et, ns:et, enable_keep_helm, no-changes, rel:et-msg-handler-pr-355

#427 RET-4715 - Bump packages
  build.gradle
Labels: prd:et, ns:et, rel:et-msg-handler-pr-427
