Repository hmcts/et-message-handler, pull requests merged in 2024-03, with the labels that each got.

#370 CHG5015458 - V15 DB Switchover
  charts/et-msg-handler/Chart.yaml
  charts/et-msg-handler/values.yaml
Labels: prd:et, ns:et, rel:et-msg-handler-pr-370

#361 RET-4687 - Add send notification flow
  build.gradle
  config/owasp/suppressions.xml
  src/main/java/uk/gov/hmcts/reform/ethos/ecm/consumer/service/SingleUpdateService.java
  src/test/java/uk/gov/hmcts/reform/ethos/ecm/consumer/service/SingleUpdateServiceTest.java
Labels: prd:et, ns:et, rel:et-msg-handler-pr-361

#397 Update App Insights
  Dockerfile
Labels: prd:et, ns:et, rel:et-msg-handler-pr-397
