Repository hmcts/et-message-handler, pull requests merged in 2024-07, with the labels that each got.

#538 RET-5296: Multithreading
  src/main/java/uk/gov/hmcts/reform/ethos/ecm/consumer/config/ServiceBusCreateUpdatesReceiverConf.java
  src/main/java/uk/gov/hmcts/reform/ethos/ecm/consumer/config/ServiceBusUpdateCaseReceiverConf.java
  src/main/java/uk/gov/hmcts/reform/ethos/ecm/consumer/tasks/CreateUpdatesBusReceiverTask.java
  src/main/java/uk/gov/hmcts/reform/ethos/ecm/consumer/tasks/UpdateCaseBusReceiverTask.java
  src/main/resources/application-cftlib.properties
  src/main/resources/application.properties
  src/test/java/uk/gov/hmcts/reform/ethos/ecm/consumer/helpers/TransferToEcmCaseDataHelperTest.java
  src/test/java/uk/gov/hmcts/reform/ethos/ecm/consumer/idam/TokenResponseTest.java
  src/test/java/uk/gov/hmcts/reform/ethos/ecm/consumer/service/AccessTokenServiceTest.java
  src/test/java/uk/gov/hmcts/reform/ethos/ecm/consumer/service/EmailServiceTest.java
  src/test/java/uk/gov/hmcts/reform/ethos/ecm/consumer/service/LegalRepAccessServiceTest.java
  src/test/java/uk/gov/hmcts/reform/ethos/ecm/consumer/service/MultipleUpdateServiceTest.java
  src/test/java/uk/gov/hmcts/reform/ethos/ecm/consumer/service/SingleCreationServiceTest.java
  src/test/java/uk/gov/hmcts/reform/ethos/ecm/consumer/service/SingleReadingServiceTest.java
  src/test/java/uk/gov/hmcts/reform/ethos/ecm/consumer/service/SingleTransferServiceTest.java
  src/test/java/uk/gov/hmcts/reform/ethos/ecm/consumer/service/SingleUpdateServiceTest.java
  src/test/java/uk/gov/hmcts/reform/ethos/ecm/consumer/service/UpdateManagementServiceTest.java
  src/test/java/uk/gov/hmcts/reform/ethos/ecm/consumer/service/UserServiceTest.java
  src/test/java/uk/gov/hmcts/reform/ethos/ecm/consumer/service/transfertoecm/CreateEcmSingleServiceTest.java
  src/test/java/uk/gov/hmcts/reform/ethos/ecm/consumer/service/transfertoecm/TransferToEcmServiceTest.java
  src/test/java/uk/gov/hmcts/reform/ethos/ecm/consumer/servicebus/MessageAutoCompletorTest.java
  src/test/java/uk/gov/hmcts/reform/ethos/ecm/consumer/tasks/CreateUpdatesBusReceiverTaskTest.java
  src/test/java/uk/gov/hmcts/reform/ethos/ecm/consumer/tasks/UpdateCaseBusReceiverTaskTest.java
Labels: prd:et, ns:et, rel:et-msg-handler-pr-538

#540 RET-5296: Add Env Var names
  src/main/resources/application-cftlib.properties
  src/main/resources/application-dev.properties
  src/main/resources/application.properties
Labels: prd:et, ns:et, rel:et-msg-handler-pr-540

#545 Sonar fixes
  src/test/java/uk/gov/hmcts/reform/ethos/ecm/consumer/service/LegalRepAccessServiceTest.java
  src/test/java/uk/gov/hmcts/reform/ethos/ecm/consumer/service/UpdateManagementServiceTest.java
Labels: prd:et, ns:et, rel:et-msg-handler-pr-545
